DIC_LEADER={
    "Azerbaijan": "Aliyev",
    "Albania": "Begaj",
    "Armenia": "Khachaturyan",
    "Bosnia and Herzegovina": "Schmidt",
    "Bulgaria": "Donev AND Донев",
    "Cyprus": "Anastasiades",
    "Denmark": "Frederiksen",
    "Ireland": "Martin",
    "Estonia": "Kallas",
    "Austria": "Nehammer",
    "Czech Republic": "Fiala",
    "Finland": "Marin",
    "France": "Macron",
    "Georgia": "Garibashvili",
    "Germany": "Scholz",
    "Greece": "Mitsotakis AND Μητσοτάκης",
    "Croatia": "Plenković",
    "Hungary": "Orbán",
    "Iceland": "Jakobsdóttir",
    "Israel": "Lapid",
    "Italy": "Meloni",
    "Latvia": "Kariņš",
    "Belarus": "Lukashenko AND Лукашэнка",
    "Lithuania": "Nausėda",
    "Slovakia": "Heger",
    "Liechtenstein": "Alois",
    "The former Yugoslav Republic of Macedonia": "Kovačevski AND Ковачевски",
    "Malta": "Abela",
    "Belgium": "De Croo",
    "Faroe Islands": "Steig Nielsen",
    "Andorra": "Zamora",
    "Luxembourg": "Bettel",
    "Monaco": "Albert II",
    "Montenegro": "Abazović AND Абазовић",
    "Netherlands": "Rutte",
    "Norway": "Støre",
    "Poland": "Morawiecki",
    "Portugal": "Costa",
    "Romania": "Iohannis",
    "Republic of Moldova": "Gavrilița",
    "Slovenia": "Golob",
    "Spain": "Sánchez",
    "Sweden": "Kristersson",
    "Switzerland": "Cassis",
    "Turkey": "Erdoğan",
    "United Kingdom": "Sunak",
    "Ukraine": "Zelenskyy",
    "San Marino": "Berti",
    "Serbia": "Brnabić AND Брнабић",
    "Holy See (Vatican City)": "Francis",
    "Russia": "Putin AND Пу́тин"
}
